---
version: "2"
services:
  emby:
    image: linuxserver/emby
    container_name: emby
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - ./emby/config:/config
      - /mnt/media:/mnt
    ports:
      - 8090:8096
    restart: unless-stopped
  
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Dhaka
    volumes:
      - ./transmission/config:/config
      - /mnt/media/torrents:/mnt/media/torrents
    ports:
      - 9091:9091
      - 49153:49153
      - 49153:49153/udp
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Dhaka
    volumes:
      - ./jackett/config:/config
      - /mnt/media/torrents/completed:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

  sonarr:
      image: linuxserver/sonarr
      container_name: sonarr
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Asia/Dhaka
        - UMASK_SET=022
      volumes:
        - ./sonarr/config:/config
        - /mnt/media:/mnt/media
      ports:
        - 8989:8989
      restart: unless-stopped
  
  radarr:
      image: linuxserver/radarr
      container_name: radarr
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Asia/Dhaka
      volumes:
        - ./radarr/config:/config
        - /mnt/media:/mnt/media
      ports:
        - 7878:7878
      restart: unless-stopped
  
  ombi:
      image: linuxserver/ombi
      container_name: ombi
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Asia/Dhaka
        - BASE_URL=/ombi
      volumes:
        - ./ombi/config:/config
      ports:
        - 3579:3579
      restart: unless-stopped
  
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/London
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped
  
  aria2:
    image: xujinkai/aria2-with-webui
    container_name: aria2
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Dhaka
      - SECRET=123456
    volumes:
      - ./aria2/config:/conf
      - /mnt/media/torrents:/data
    ports:
      - 6880:80
    restart: unless-stopped
